[package]
name = "nester"
version = "0.2.0"
edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
dirs = "5.0"
git2 = "0.18"
serde = { version = "1.0", features = ["derive"] }
tera = "1.20"
toml = "0.8"
