[package]
name = "nester"
version = "1.0.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.37", features = ["derive"] }
dirs = "6.0.0"
git2 = "0.20.1"
serde = { version = "1.0.219", features = ["derive"] }
tera = "1.20.0"
toml = "0.8.22"
